import { writeFileSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildApiSchemaManifest } from '../src/server/server-adapter/api-schema-manifest';

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), '../../..');
const outputPath = resolve(rootDir, join('packages', 'cli', 'src', 'commands', 'api', 'route-metadata.generated.ts'));

const apiSchemaManifest = buildApiSchemaManifest();

const metadata = Object.fromEntries(
  apiSchemaManifest.routes.map(route => [
    `${route.method} ${route.path}`,
    {
      method: route.method,
      path: route.path,
      pathParams: extractPathParams(route.path),
      queryParams: extractSchemaProperties(route.queryParamSchema),
      bodyParams: extractSchemaProperties(route.bodySchema),
      hasQuery: Boolean(route.queryParamSchema),
      hasBody: Boolean(route.bodySchema),
      responseShape: route.responseShape,
    },
  ]),
);

writeFileSync(
  outputPath,
  `// This file is generated by packages/server/scripts/generate-api-cli-route-metadata.ts. Do not edit by hand.\n\n` +
    `export const API_ROUTE_METADATA = ${JSON.stringify(metadata, null, 2)} as const;\n`,
);

function extractPathParams(path: string): string[] {
  return [...path.matchAll(/:([A-Za-z0-9_]+)/g)]
    .map(match => match[1])
    .filter((value): value is string => Boolean(value));
}

function extractSchemaProperties(schema: { properties?: unknown } | undefined): string[] {
  if (!schema?.properties || typeof schema.properties !== 'object' || Array.isArray(schema.properties)) return [];
  return Object.keys(schema.properties).sort();
}
