export { EditorNamespace, CrudEditorNamespace } from './base';
export type { StorageAdapter } from './base';
export { EditorAgentNamespace } from './agent';
export { EditorMCPNamespace } from './mcp';
export { EditorMCPServerNamespace } from './mcp-server';
export { EditorPromptNamespace } from './prompt';
export { EditorScorerNamespace } from './scorer';
export { EditorWorkspaceNamespace } from './workspace';
export { EditorSkillNamespace } from './skill';
export { EditorFavoritesNamespace } from './favorites';
