/**
 * Tests for Anthropic server-side fallback detection.
 *
 * When the primary model's safety classifiers decline a turn and a fallback
 * chain is configured, the response is generated by the fallback model and
 * reported via `fallback_message` entries in
 * `providerMetadata.anthropic.iterations`. Tracing/metrics must attribute the
 * turn to the model that actually served it.
 */
import { describe, it, expect } from 'vitest';
import { getServerSideFallbackInfo, resolveResponseModelId } from './server-side-fallback';

describe('getServerSideFallbackInfo', () => {
  it('returns the fallback model that served the turn', () => {
    expect(
      getServerSideFallbackInfo({
        anthropic: {
          iterations: [
            { type: 'message', model: 'claude-fable-5', inputTokens: 10, outputTokens: 0 },
            { type: 'fallback_message', model: 'claude-opus-4-7', inputTokens: 10, outputTokens: 50 },
          ],
        },
      }),
    ).toEqual({ model: 'claude-opus-4-7' });
  });

  it('returns the last fallback iteration when multiple fallbacks fired', () => {
    expect(
      getServerSideFallbackInfo({
        anthropic: {
          iterations: [
            { type: 'fallback_message', model: 'fallback-a', inputTokens: 1, outputTokens: 0 },
            { type: 'fallback_message', model: 'fallback-b', inputTokens: 1, outputTokens: 50 },
          ],
        },
      }),
    ).toEqual({ model: 'fallback-b' });
  });

  it('returns an empty info object when the fallback iteration has no model id', () => {
    expect(
      getServerSideFallbackInfo({
        anthropic: { iterations: [{ type: 'fallback_message', inputTokens: 10, outputTokens: 50 }] },
      }),
    ).toEqual({});
  });

  it('returns undefined when no fallback iteration is present', () => {
    expect(
      getServerSideFallbackInfo({
        anthropic: { iterations: [{ type: 'message', model: 'claude-fable-5', inputTokens: 10, outputTokens: 50 }] },
      }),
    ).toBeUndefined();
  });

  it('returns undefined when iterations are absent or malformed', () => {
    expect(getServerSideFallbackInfo(undefined)).toBeUndefined();
    expect(getServerSideFallbackInfo({})).toBeUndefined();
    expect(getServerSideFallbackInfo({ anthropic: {} })).toBeUndefined();
    expect(getServerSideFallbackInfo({ anthropic: { iterations: 'nope' } })).toBeUndefined();
  });
});

describe('resolveResponseModelId', () => {
  it('prefers the fallback model over the response model id', () => {
    expect(
      resolveResponseModelId(
        { anthropic: { iterations: [{ type: 'fallback_message', model: 'claude-opus-4-7' }] } },
        'claude-fable-5',
      ),
    ).toBe('claude-opus-4-7');
  });

  it('falls back to the response model id when no server-side fallback fired', () => {
    expect(resolveResponseModelId(undefined, 'claude-fable-5')).toBe('claude-fable-5');
    expect(
      resolveResponseModelId(
        { anthropic: { iterations: [{ type: 'message', model: 'claude-fable-5' }] } },
        'claude-fable-5',
      ),
    ).toBe('claude-fable-5');
  });

  it('falls back to the response model id when the fallback iteration has no model', () => {
    expect(
      resolveResponseModelId({ anthropic: { iterations: [{ type: 'fallback_message' }] } }, 'claude-fable-5'),
    ).toBe('claude-fable-5');
  });

  it('returns undefined when neither source is available', () => {
    expect(resolveResponseModelId(undefined, undefined)).toBeUndefined();
  });
});
