/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Login
     * @description Redirect to WorkOS authorization URL. Supports studio (browser), deploy (browser), and cli (token) flows.
     */
    get: operations['getV1AuthLogin'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/callback': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * OAuth callback
     * @description Handle WorkOS OAuth callback. Creates session (browser) or passes tokens (CLI). Not called directly by clients.
     */
    get: operations['getV1AuthCallback'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/verify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Verify CLI token
     * @description Verify a CLI bearer token (WorkOS JWT or WorkOS API key) and return user info and organization.
     */
    get: operations['getV1AuthVerify'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/ingest/verify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Verify ingest token
     * @description Verify a WorkOS Organization API key for telemetry ingest and confirm access to the requested project.
     */
    post: operations['postV1AuthIngestVerify'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/refresh-token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Refresh access token
     * @description Exchange a WorkOS refresh token for a new access token (CLI flow).
     */
    post: operations['postV1AuthRefreshToken'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Refresh session
     * @description Refresh the sealed session cookie using WorkOS refresh token.
     */
    get: operations['getV1AuthRefresh'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get current user
     * @description Return the current session user, organization, role, and permissions.
     */
    get: operations['getV1AuthMe'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/orgs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List organizations
     * @description List organizations the user belongs to. Accepts Bearer token (CLI) or session cookie (browser).
     */
    get: operations['getV1AuthOrgs'];
    put?: never;
    /**
     * Create organization
     * @description Create a new organization and auto-switch the session to it.
     */
    post: operations['postV1AuthOrgs'];
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update organization
     * @description Update the current organization name. Requires admin role.
     */
    patch: operations['patchV1AuthOrgs'];
    trace?: never;
  };
  '/v1/auth/switch-org': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Switch organization
     * @description Switch the current session to a different organization.
     */
    post: operations['postV1AuthSwitchOrg'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Logout
     * @description Clear session cookie and return optional WorkOS logout URL.
     */
    post: operations['postV1AuthLogout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/org/members': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List members
     * @description List all members of the current organization.
     */
    get: operations['getV1OrgMembers'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/org/members/invitations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List invitations
     * @description List all pending invitations for the current organization.
     */
    get: operations['getV1OrgMembersInvitations'];
    put?: never;
    /**
     * Send invitation
     * @description Send an invitation to join the organization. Requires admin role.
     */
    post: operations['postV1OrgMembersInvitations'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/org/members/invitations/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Revoke invitation
     * @description Revoke a pending invitation. Requires admin role.
     */
    delete: operations['deleteV1OrgMembersInvitationsById'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/org/members/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Remove member
     * @description Remove a member from the organization. Requires admin role.
     */
    delete: operations['deleteV1OrgMembersById'];
    options?: never;
    head?: never;
    /**
     * Update member role
     * @description Update the role of a member in the organization. Requires admin role.
     */
    patch: operations['patchV1OrgMembersById'];
    trace?: never;
  };
  '/v1/gateway/projects/{id}/usage/has-activity': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Check if project has any usage activity
     * @description Lightweight check — returns true if the project has ever received at least one request.
     */
    get: operations['getV1GatewayProjectsByIdUsageHasActivity'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/gateway/projects/{id}/usage/activity': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get usage activity
     * @description Aggregated usage metrics for a project. Supports multiple granularities (1m, 5m, 15m, 1h, daily, weekly, monthly) and optional group-by dimensions (model, provider, source_category, api_key_id).
     */
    get: operations['getV1GatewayProjectsByIdUsageActivity'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/gateway/projects/{id}/usage/memory-activity': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get memory token activity
     * @description Aggregated memory token totals for a project. Supports 1h, daily, weekly, and monthly granularities.
     */
    get: operations['getV1GatewayProjectsByIdUsageMemoryActivity'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/gateway/projects/{id}/usage/logs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get request logs
     * @description Per-request log entries for a project. Supports filtering by model, provider, source, and API key. Paginated with limit/offset (max 200 per page, default 50).
     */
    get: operations['getV1GatewayProjectsByIdUsageLogs'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/gateway/projects/{id}/usage/logs/facets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get log facet counts
     * @description Returns distinct values and counts for filterable fields, respecting all active filters except the field being faceted.
     */
    get: operations['getV1GatewayProjectsByIdUsageLogsFacets'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/gateway/projects/{id}/usage/logs/{requestId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a single request log with messages
     * @description Returns the full request log entry enriched with API key info, plus any associated messages fetched via message_ids.
     */
    get: operations['getV1GatewayProjectsByIdUsageLogsByRequestId'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/studio/projects': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List projects
     * @description List all projects for the current organization
     */
    get: operations['getV1StudioProjects'];
    put?: never;
    /**
     * Create project
     * @description Create a new project
     */
    post: operations['postV1StudioProjects'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/studio/projects/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get project
     * @description Get project details and all deploys
     */
    get: operations['getV1StudioProjectsById'];
    put?: never;
    post?: never;
    /**
     * Delete project
     * @description Delete a project and all its deploys
     */
    delete: operations['deleteV1StudioProjectsById'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/studio/deploys': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create deploy
     * @description Create a new deployment. When an artifact store is configured, returns a signed upload URL for the client to upload the zip directly. Otherwise accepts the zip body directly (legacy).
     */
    post: operations['postV1StudioDeploys'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/studio/deploys/{id}/upload-complete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Confirm artifact upload
     * @description Signal that the client has finished uploading the artifact to the signed URL. Triggers the deploy pipeline.
     */
    post: operations['postV1StudioDeploysByIdUploadComplete'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/studio/deploys/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get deploy status
     * @description Get the current status of a deployment
     */
    get: operations['getV1StudioDeploysById'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/studio/deploys/{id}/cancel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Cancel studio deploy
     * @description Cancel a queued or uploading deployment before the pipeline starts.
     */
    post: operations['postV1StudioDeploysByIdCancel'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/studio/deploys/{id}/logs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get deploy logs
     * @description Get combined stdout and stderr logs for a deployment
     */
    get: operations['getV1StudioDeploysByIdLogs'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/studio/deploys/{id}/logs/stream': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Stream deploy logs
     * @description Stream deployment logs in real-time via Server-Sent Events
     */
    get: operations['getV1StudioDeploysByIdLogsStream'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/server/projects': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List server projects
     * @description List all server projects for the current organization
     */
    get: operations['getV1ServerProjects'];
    put?: never;
    /**
     * Create server project
     * @description Create a new server project
     */
    post: operations['postV1ServerProjects'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/server/projects/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get server project
     * @description Get server project details and all deploys
     */
    get: operations['getV1ServerProjectsById'];
    put?: never;
    post?: never;
    /**
     * Delete server project
     * @description Delete a server project and its resources
     */
    delete: operations['deleteV1ServerProjectsById'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/server/projects/{id}/env': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get environment variables
     * @description Get environment variables for a server project
     */
    get: operations['getV1ServerProjectsByIdEnv'];
    /**
     * Update environment variables
     * @description Update environment variables for a server project
     */
    put: operations['putV1ServerProjectsByIdEnv'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/server/projects/{id}/env/restart': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Update environment variables and restart service
     * @description Update environment variables for a server project and restart the service to apply changes immediately
     */
    post: operations['postV1ServerProjectsByIdEnvRestart'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/server/projects/{id}/domains': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get project domains
     * @description Get all domains for a server project
     */
    get: operations['getV1ServerProjectsByIdDomains'];
    put?: never;
    /**
     * Add custom domain
     * @description Add a custom domain to a server project
     */
    post: operations['postV1ServerProjectsByIdDomains'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/server/projects/{id}/runtime-logs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get runtime logs
     * @description Get runtime logs for the latest deployment of a server project
     */
    get: operations['getV1ServerProjectsByIdRuntimeLogs'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/server/projects/{id}/redeploy': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Redeploy project
     * @description Trigger a new deployment for a server project
     */
    post: operations['postV1ServerProjectsByIdRedeploy'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/server/projects/{id}/pause': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Pause server
     * @description Stop the currently running deploy for a server project. The server will no longer respond to requests until restarted.
     */
    post: operations['postV1ServerProjectsByIdPause'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/server/projects/{id}/restart': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Restart server
     * @description Trigger a new deployment for a stopped, failed, crashed, or cancelled server project.
     */
    post: operations['postV1ServerProjectsByIdRestart'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/server/deploys': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create server deploy
     * @description Create a new deployment. Returns a signed upload URL — the client uploads the artifact ZIP there, then calls POST /deploys/:id/upload-complete.
     */
    post: operations['postV1ServerDeploys'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/server/deploys/{id}/upload-complete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Confirm artifact upload
     * @description Signal that the artifact ZIP has been uploaded. Triggers the build → deploy pipeline.
     */
    post: operations['postV1ServerDeploysByIdUploadComplete'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/server/deploys/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get server deploy status
     * @description Get the current status of a server deployment
     */
    get: operations['getV1ServerDeploysById'];
    put?: never;
    post?: never;
    /**
     * Stop server deploy
     * @description Stop a server deployment
     */
    delete: operations['deleteV1ServerDeploysById'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/server/deploys/{id}/logs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get server deploy logs
     * @description Get build and deploy logs for a deployment
     */
    get: operations['getV1ServerDeploysByIdLogs'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/server/deploys/{id}/cancel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Cancel server deploy
     * @description Cancel a queued or in-progress deployment
     */
    post: operations['postV1ServerDeploysByIdCancel'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/support/tickets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create a support ticket
     * @description Submit a support ticket via Pylon.
     */
    post: operations['postV1SupportTickets'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getV1AuthLogin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Redirect to WorkOS authorization URL */
      302: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getV1AuthCallback: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Redirect to application or CLI callback */
      302: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Access denied — user does not belong to the requested organization */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
      /** @description Session creation failed */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  getV1AuthVerify: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Token valid */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            user: {
              id: string;
              email: string | null;
              firstName: string | null;
              lastName: string | null;
            };
            organizationId: string;
            role?: string;
            /** @enum {string} */
            authType?: 'user' | 'api-key';
            memberOrgIds?: string[];
          };
        };
      };
      /** @description Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
      /** @description Not a member of the organization */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  postV1AuthIngestVerify: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          projectId: string;
        };
      };
    };
    responses: {
      /** @description Token valid for project ingest */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            organizationId: string;
            projectId: string;
            /** @constant */
            authType: 'api-key';
          };
        };
      };
      /** @description Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
      /** @description Valid bearer token but not a WorkOS API key */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
      /** @description Project not found or inaccessible */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  postV1AuthRefreshToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          refreshToken: string;
        };
      };
    };
    responses: {
      /** @description New tokens */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            accessToken: string;
            refreshToken: string;
          };
        };
      };
      /** @description Refresh failed */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  getV1AuthRefresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session refreshed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @constant */
            ok: true;
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  getV1AuthMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current session info */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            user: {
              id: string;
              email: string;
              firstName: string | null;
              lastName: string | null;
              profilePictureUrl: string | null;
            };
            organizationId: string | null;
            role: string | null;
            permissions: string[];
            memberOrgIds: string[];
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  getV1AuthOrgs: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of organizations */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            organizations: {
              id: string;
              name: string;
              role: string | null;
              isCurrent: boolean;
            }[];
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  postV1AuthOrgs: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          name: string;
        };
      };
    };
    responses: {
      /** @description Organization created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            organization: {
              id: string;
              name: string;
              role: string | null;
              isCurrent: boolean;
            };
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  patchV1AuthOrgs: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          name: string;
        };
      };
    };
    responses: {
      /** @description Organization updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            organization: {
              id: string;
              name: string;
              role: string | null;
              isCurrent: boolean;
            };
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
      /** @description Forbidden — not an admin */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  postV1AuthSwitchOrg: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          organizationId: string;
        };
      };
    };
    responses: {
      /** @description Organization switched */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @constant */
            ok: true;
            organizationId: string;
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  postV1AuthLogout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** Format: uri */
          returnTo?: string;
        };
      };
    };
    responses: {
      /** @description Logged out */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @constant */
            ok: true;
            logoutUrl?: string;
          };
        };
      };
    };
  };
  getV1OrgMembers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of members */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            members: {
              id: string;
              userId: string;
              email: string;
              firstName: string | null;
              lastName: string | null;
              profilePictureUrl: string | null;
              role: string | null;
              status: string;
              createdAt: string;
            }[];
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
      /** @description Forbidden — no organization selected */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  getV1OrgMembersInvitations: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of invitations */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            invitations: {
              id: string;
              email: string;
              state: string;
              expiresAt: string;
              createdAt: string;
            }[];
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
      /** @description Forbidden — no organization selected */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  postV1OrgMembersInvitations: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** Format: email */
          email: string;
          /** @enum {string} */
          role: 'member' | 'admin';
        };
      };
    };
    responses: {
      /** @description Invitation sent */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            invitation: {
              id: string;
              email: string;
              state: string;
              expiresAt: string;
              createdAt: string;
            };
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
      /** @description Forbidden — admin role required */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  deleteV1OrgMembersInvitationsById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Invitation revoked */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @constant */
            ok: true;
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
      /** @description Forbidden — admin role required */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  deleteV1OrgMembersById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Member removed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @constant */
            ok: true;
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
      /** @description Forbidden — admin role required */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  patchV1OrgMembersById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** @enum {string} */
          role: 'member' | 'admin';
        };
      };
    };
    responses: {
      /** @description Member role updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            member: {
              id: string;
              userId: string;
              email: string;
              firstName: string | null;
              lastName: string | null;
              profilePictureUrl: string | null;
              role: string | null;
              status: string;
              createdAt: string;
            };
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
      /** @description Forbidden — admin role required */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  getV1GatewayProjectsByIdUsageHasActivity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Activity check result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            has_activity: boolean;
          };
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  getV1GatewayProjectsByIdUsageActivity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Usage activity data */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            project_id: string;
            from: string;
            to: string;
            /** @enum {string} */
            granularity: 'daily' | 'weekly' | 'monthly' | '1h';
            group_by: string[];
            data:
              | {
                  request_count: number;
                  error_count: number;
                  prompt_tokens: number;
                  completion_tokens: number;
                  total_tokens: number;
                  cached_tokens: number;
                  cache_write_tokens: number;
                  uncached_tokens: number;
                  cache_hit_rate: number;
                  cost_usd: number;
                  error_rate: number;
                  avg_cost_per_request: number;
                }
              | {
                  request_count: number;
                  error_count: number;
                  prompt_tokens: number;
                  completion_tokens: number;
                  total_tokens: number;
                  cached_tokens: number;
                  cache_write_tokens: number;
                  uncached_tokens: number;
                  cache_hit_rate: number;
                  cost_usd: number;
                  error_rate: number;
                  avg_cost_per_request: number;
                  timestamp: string;
                  model?: string;
                  provider?: string;
                  source?: string;
                  source_category?: string;
                  api_key_id?: string | null;
                  api_key_label?: string | null;
                  api_key_prefix?: string | null;
                  endpoint?: string;
                  status_code?: number;
                }[];
          };
        };
      };
      /** @description Invalid query parameters */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  getV1GatewayProjectsByIdUsageMemoryActivity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Memory token activity data */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            projectId: string;
            from: string;
            to: string;
            /** @enum {string} */
            granularity: '1h' | 'daily' | 'weekly' | 'monthly';
            data: {
              bucket: string;
              promptTokens: number;
              completionTokens: number;
              totalTokens: number;
              apiKeyId?: string | null;
              apiKeyLabel?: string | null;
              apiKeyPrefix?: string | null;
            }[];
          };
        };
      };
      /** @description Invalid query parameters */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  getV1GatewayProjectsByIdUsageLogs: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request log entries */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            project_id: string;
            from: string;
            to: string;
            logs: {
              request_id: string;
              api_key_id: string | null;
              api_key_label: string | null;
              api_key_prefix: string | null;
              model: string;
              provider: string;
              source: string;
              source_category: string;
              endpoint: string;
              status_code: number;
              prompt_tokens: number;
              completion_tokens: number;
              total_tokens: number;
              cached_tokens: number;
              cache_write_tokens: number;
              cost_usd: number;
              latency_ms: number;
              is_stream: boolean;
              error: string | null;
              generation_id: string | null;
              thread_id: string | null;
              resource_id: string | null;
              message_ids: string[];
              timestamp: string;
            }[];
            has_more: boolean;
          };
        };
      };
      /** @description Invalid query parameters */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  getV1GatewayProjectsByIdUsageLogsFacets: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Facet counts per field */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            status_code: {
              value: string;
              count: number;
            }[];
            model: {
              value: string;
              count: number;
            }[];
            provider: {
              value: string;
              count: number;
            }[];
            source: {
              value: string;
              count: number;
            }[];
            source_category: {
              value: string;
              count: number;
            }[];
            has_error: {
              value: string;
              count: number;
            }[];
            endpoint: {
              value: string;
              count: number;
            }[];
            is_stream: {
              value: string;
              count: number;
            }[];
          };
        };
      };
      /** @description Invalid query parameters */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  getV1GatewayProjectsByIdUsageLogsByRequestId: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        requestId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Log detail with messages */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            log: {
              request_id: string;
              api_key_id: string | null;
              api_key_label: string | null;
              api_key_prefix: string | null;
              model: string;
              provider: string;
              source: string;
              source_category: string;
              endpoint: string;
              status_code: number;
              prompt_tokens: number;
              completion_tokens: number;
              total_tokens: number;
              cached_tokens: number;
              cache_write_tokens: number;
              cost_usd: number;
              latency_ms: number;
              is_stream: boolean;
              error: string | null;
              generation_id: string | null;
              thread_id: string | null;
              resource_id: string | null;
              message_ids: string[];
              timestamp: string;
            };
            messages: {
              id: string;
              threadId: string;
              role: string;
              content: unknown;
              type: string;
              createdAt: string;
            }[];
          };
        };
      };
      /** @description Project or log not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  getV1StudioProjects: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of projects */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            projects: {
              id: string;
              slug: string;
              name: string;
              organizationId: string;
              studioEnabled: boolean;
              serverEnabled: boolean;
              latestDeployId: string | null;
              latestDeployStatus:
                | ('queued' | 'starting' | 'running' | 'stopped' | 'failed' | 'cancelled' | 'unknown')
                | null;
              latestDeployCreatedAt: string | null;
              latestServerDeployStatus: string | null;
              customServerApiUrl: string | null;
              instanceUrl: string | null;
              serverInstanceUrl: string | null;
              createdAt: string | null;
              updatedAt: string | null;
            }[];
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  postV1StudioProjects: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          name: string;
        };
      };
    };
    responses: {
      /** @description Created project */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            project: {
              id: string;
              slug: string;
              name: string;
              organizationId: string;
              studioEnabled: boolean;
              serverEnabled: boolean;
              latestDeployId: string | null;
              latestDeployStatus:
                | ('queued' | 'starting' | 'running' | 'stopped' | 'failed' | 'cancelled' | 'unknown')
                | null;
              latestDeployCreatedAt: string | null;
              latestServerDeployStatus: string | null;
              customServerApiUrl: string | null;
              instanceUrl: string | null;
              serverInstanceUrl: string | null;
              createdAt: string | null;
              updatedAt: string | null;
            };
          };
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  getV1StudioProjectsById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Project with deploys */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            project: {
              id: string;
              slug: string;
              name: string;
              organizationId: string;
              studioEnabled: boolean;
              serverEnabled: boolean;
              latestDeployId: string | null;
              latestDeployStatus:
                | ('queued' | 'starting' | 'running' | 'stopped' | 'failed' | 'cancelled' | 'unknown')
                | null;
              latestDeployCreatedAt: string | null;
              latestServerDeployStatus: string | null;
              customServerApiUrl: string | null;
              instanceUrl: string | null;
              serverInstanceUrl: string | null;
              createdAt: string | null;
              updatedAt: string | null;
            };
            deploys: {
              id: string;
              projectId: string;
              organizationId: string;
              projectName: string;
              /** @enum {string} */
              status: 'queued' | 'starting' | 'running' | 'stopped' | 'failed' | 'cancelled' | 'unknown';
              instanceUrl: string | null;
              error: string | null;
              createdAt: string | null;
            }[];
          };
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  deleteV1StudioProjectsById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Project deleted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @constant */
            ok: true;
          };
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  postV1StudioDeploys: {
    parameters: {
      query?: never;
      header?: {
        'x-project-id'?: string;
        'x-project-name'?: string;
        'x-git-branch'?: string;
        'x-mastra-version'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': {
          envVars?: {
            [key: string]: string;
          };
          disablePlatformObservability?: boolean;
        };
      };
    };
    responses: {
      /** @description Deploy queued */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            deploy: {
              id: string;
              /** @constant */
              status: 'queued';
              uploadUrl?: string;
            };
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  postV1StudioDeploysByIdUploadComplete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Upload confirmed, pipeline started */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @constant */
            status: 'ok';
          };
        };
      };
      /** @description Deploy not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  getV1StudioDeploysById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deploy info */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            deploy: {
              id: string;
              projectId: string;
              organizationId: string;
              projectName: string;
              /** @enum {string} */
              status: 'queued' | 'starting' | 'running' | 'stopped' | 'failed' | 'cancelled' | 'unknown';
              instanceUrl: string | null;
              error: string | null;
              createdAt: string | null;
            };
          };
        };
      };
      /** @description Deploy not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  postV1StudioDeploysByIdCancel: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deploy cancelled */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            id: string;
            /** @enum {string} */
            status: 'queued' | 'starting' | 'running' | 'stopped' | 'failed' | 'cancelled' | 'unknown';
          };
        };
      };
      /** @description Deploy cannot be cancelled (not in queued or uploading state) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
      /** @description Deploy not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  getV1StudioDeploysByIdLogs: {
    parameters: {
      query?: {
        /** @description Number of recent log lines to return */
        tail?: string;
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deploy logs */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            logs: string;
          };
        };
      };
      /** @description Deploy not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  getV1StudioDeploysByIdLogsStream: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description SSE stream of log lines */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/event-stream': string;
        };
      };
      /** @description Deploy not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  getV1ServerProjects: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of server projects */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            projects: {
              id: string;
              name: string;
              slug: string | null;
              organizationId: string;
              studioEnabled: boolean;
              serverEnabled: boolean;
              alwaysOn: boolean;
              providerProjectId: string | null;
              providerServiceId: string | null;
              providerEnvironmentId: string | null;
              repo: string | null;
              branch: string | null;
              lastDeployedCommitSha: string | null;
              lastDeployedImageUrl: string | null;
              lastDeployedDockerfileHash: string | null;
              latestDeployId: string | null;
              latestDeployStatus: string | null;
              instanceUrl: string | null;
              createdAt: string | null;
              updatedAt: string | null;
            }[];
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
          };
        };
      };
    };
  };
  postV1ServerProjects: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          name: string;
        };
      };
    };
    responses: {
      /** @description Created server project */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            project: {
              id: string;
              name: string;
              slug: string | null;
              organizationId: string;
              studioEnabled: boolean;
              serverEnabled: boolean;
              alwaysOn: boolean;
              providerProjectId: string | null;
              providerServiceId: string | null;
              providerEnvironmentId: string | null;
              repo: string | null;
              branch: string | null;
              lastDeployedCommitSha: string | null;
              lastDeployedImageUrl: string | null;
              lastDeployedDockerfileHash: string | null;
              latestDeployId: string | null;
              latestDeployStatus: string | null;
              instanceUrl: string | null;
              createdAt: string | null;
              updatedAt: string | null;
            };
            deploys: {
              id: string;
              projectId: string;
              organizationId: string;
              projectName: string;
              status: string;
              instanceUrl: string | null;
              error: string | null;
              startedAt: string | null;
              stoppedAt: string | null;
              createdAt: string | null;
              updatedAt: string | null;
            }[];
          };
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
          };
        };
      };
    };
  };
  getV1ServerProjectsById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Server project with deploys */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            project: {
              id: string;
              name: string;
              slug: string | null;
              organizationId: string;
              studioEnabled: boolean;
              serverEnabled: boolean;
              alwaysOn: boolean;
              providerProjectId: string | null;
              providerServiceId: string | null;
              providerEnvironmentId: string | null;
              repo: string | null;
              branch: string | null;
              lastDeployedCommitSha: string | null;
              lastDeployedImageUrl: string | null;
              lastDeployedDockerfileHash: string | null;
              latestDeployId: string | null;
              latestDeployStatus: string | null;
              instanceUrl: string | null;
              createdAt: string | null;
              updatedAt: string | null;
            };
            deploys: {
              id: string;
              projectId: string;
              organizationId: string;
              projectName: string;
              status: string;
              instanceUrl: string | null;
              error: string | null;
              startedAt: string | null;
              stoppedAt: string | null;
              createdAt: string | null;
              updatedAt: string | null;
            }[];
          };
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
          };
        };
      };
    };
  };
  deleteV1ServerProjectsById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Project deleted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
          };
        };
      };
    };
  };
  getV1ServerProjectsByIdEnv: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Env vars */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            envVars: {
              [key: string]: string;
            };
          };
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
          };
        };
      };
    };
  };
  putV1ServerProjectsByIdEnv: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          envVars: {
            [key: string]: string;
          };
        };
      };
    };
    responses: {
      /** @description Env vars updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
          };
        };
      };
    };
  };
  postV1ServerProjectsByIdEnvRestart: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          envVars: {
            [key: string]: string;
          };
        };
      };
    };
    responses: {
      /** @description Env vars updated and service restarted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
          };
        };
      };
    };
  };
  getV1ServerProjectsByIdDomains: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Domains */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            domains: {
              domain: string;
            }[];
          };
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
          };
        };
      };
    };
  };
  postV1ServerProjectsByIdDomains: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          domain: string;
        };
      };
    };
    responses: {
      /** @description Custom domain added */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            domain: string;
            dnsRecords: {
              hostlabel: string;
              requiredValue: string;
            }[];
          };
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
          };
        };
      };
    };
  };
  getV1ServerProjectsByIdRuntimeLogs: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Runtime logs */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            logs: {
              timestamp: string;
              message: string;
              severity: string;
            }[];
          };
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
          };
        };
      };
    };
  };
  postV1ServerProjectsByIdRedeploy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deploy queued */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            id: string;
            status: string;
            uploadUrl?: string;
          };
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
          };
        };
      };
    };
  };
  postV1ServerProjectsByIdPause: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Server paused */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
          };
        };
      };
      /** @description Server is not running */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
          };
        };
      };
    };
  };
  postV1ServerProjectsByIdRestart: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deploy queued */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            id: string;
            status: string;
            uploadUrl?: string;
          };
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
          };
        };
      };
      /** @description Server is already running or deploying */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
          };
        };
      };
    };
  };
  postV1ServerDeploys: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          projectId: string;
          projectName?: string;
          envVars?: {
            [key: string]: string;
          };
          disablePlatformObservability?: boolean;
        };
      };
    };
    responses: {
      /** @description Deploy queued with upload URL */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            id: string;
            status: string;
            uploadUrl?: string;
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
          };
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
          };
        };
      };
    };
  };
  postV1ServerDeploysByIdUploadComplete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Upload confirmed, pipeline triggered */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Deploy not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
          };
        };
      };
    };
  };
  getV1ServerDeploysById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deploy info */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            id: string;
            projectId: string;
            organizationId: string;
            projectName: string;
            status: string;
            instanceUrl: string | null;
            error: string | null;
            createdAt: string | null;
            updatedAt: string | null;
          };
        };
      };
      /** @description Deploy not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
          };
        };
      };
    };
  };
  deleteV1ServerDeploysById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deploy stopped */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Deploy not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
          };
        };
      };
    };
  };
  getV1ServerDeploysByIdLogs: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Build and deploy logs */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            buildLogs: string[];
            deployLogs: string[];
          };
        };
      };
      /** @description Deploy not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
          };
        };
      };
    };
  };
  postV1ServerDeploysByIdCancel: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deploy cancelled */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            id: string;
            status: string;
          };
        };
      };
      /** @description Deploy not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
          };
        };
      };
    };
  };
  postV1SupportTickets: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          title: string;
          body: string;
          context?: {
            projectId?: string;
            product?: string;
            pageUrl?: string;
            userAgent?: string;
            viewport?: string;
            timezone?: string;
            appEnv?: string;
          };
        };
      };
    };
    responses: {
      /** @description Ticket created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            id: string;
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
      /** @description Forbidden — no organization selected */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
      /** @description Upstream Pylon error */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
      /** @description Support not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** Format: uri */
            help_url?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
}
